language: go
sudo: false

go:
- 1.4.3
- 1.5.3
- 1.6.0
- tip

matrix:
  allow_failures:
    - go: tip

script:
- go tool -n vet || go get golang.org/x/tools/cmd/vet
- go vet ./...
- go test -v -race ./...
